{
 "title": "Concurrency",
 "time": { "from": "2020-06-07T16:23:55.998Z", "to": "2020-06-07T16:49:44.834Z" },
 "panels": [
  {
   "title": "No SQS, Batch 10, Concurrency 1000",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SQS, Batch 1, Concurrency 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SQS, Batch 1, Concurrency 1000",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1s),\n  count(id) AS \"id\"\nFROM invocation\nWHERE \n  $__timeFilter(created_at) AND group_id = 'consumer-1'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1s),\n  count(id) AS \"id\"\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND group_id = 'consumer-2'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1s),\n  count(id) AS \"id\"\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND group_id = 'consumer-3'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "No SQS, Batch 10, Concurrency 1000",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SQS, Batch 1, Concurrency 1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SQS, Batch 1, Concurrency 1000",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-3'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  cache_id AS metric,\n  count(id) AS \"id\"\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-1'\nGROUP BY 1, cache_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  cache_id AS metric,\n  count(id) AS \"id\"\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-2'\nGROUP BY 1, cache_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  cache_id AS metric,\n  count(id) AS \"id\"\nFROM invocation\nWHERE\n  $__timeFilter(created_at) AND\n  group_id = 'consumer-3'\nGROUP BY 1, cache_id,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as metric FROM (SELECT DISTINCT cache_id FROM invocation WHERE group_id = 'consumer-1') AS metric;"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as metric FROM (SELECT DISTINCT cache_id FROM invocation WHERE group_id = 'consumer-2') AS metric;"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as metric FROM (SELECT DISTINCT cache_id FROM invocation WHERE group_id = 'consumer-3') AS metric;"
    }
   ]
  }
 ]
}