Resources:
  DemoTopic2BE41B12:
    Type: AWS::SNS::Topic
    Metadata:
      aws:cdk:path: demo/DemoTopic/Resource
  DemoConsumer1ServiceRoleB72848E3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: demo/DemoConsumer1/ServiceRole/Resource
  DemoConsumer1955F5F25:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3BucketE2ADDE75
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - DemoConsumer1ServiceRoleB72848E3
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          SERVICE_NAME: consumer-1
      Timeout: 60
    DependsOn:
      - DemoConsumer1ServiceRoleB72848E3
    Metadata:
      aws:cdk:path: demo/DemoConsumer1/Resource
      aws:asset:path: asset.9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028
      aws:asset:property: Code
  DemoConsumer1AllowInvokedemoDemoTopic3BBFFA9C989C99B0:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DemoConsumer1955F5F25
          - Arn
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: DemoTopic2BE41B12
    Metadata:
      aws:cdk:path: demo/DemoConsumer1/AllowInvoke:demoDemoTopic3BBFFA9C
  DemoConsumer1DemoTopic78019799:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn:
        Ref: DemoTopic2BE41B12
      Endpoint:
        Fn::GetAtt:
          - DemoConsumer1955F5F25
          - Arn
    Metadata:
      aws:cdk:path: demo/DemoConsumer1/DemoTopic/Resource
  DemoQueue23A6C79B0:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
    Metadata:
      aws:cdk:path: demo/DemoQueue2/Resource
  DemoQueue2Policy0A674390:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: DemoTopic2BE41B12
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - DemoQueue23A6C79B0
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: DemoQueue23A6C79B0
    Metadata:
      aws:cdk:path: demo/DemoQueue2/Policy/Resource
  DemoQueue2demoDemoTopic3BBFFA9C7E40F5C5:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn:
        Ref: DemoTopic2BE41B12
      Endpoint:
        Fn::GetAtt:
          - DemoQueue23A6C79B0
          - Arn
    Metadata:
      aws:cdk:path: demo/DemoQueue2/demoDemoTopic3BBFFA9C/Resource
  DemoConsumer2ServiceRole94782386:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: demo/DemoConsumer2/ServiceRole/Resource
  DemoConsumer2ServiceRoleDefaultPolicyC9C2B244:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DemoQueue23A6C79B0
                - Arn
        Version: "2012-10-17"
      PolicyName: DemoConsumer2ServiceRoleDefaultPolicyC9C2B244
      Roles:
        - Ref: DemoConsumer2ServiceRole94782386
    Metadata:
      aws:cdk:path: demo/DemoConsumer2/ServiceRole/DefaultPolicy/Resource
  DemoConsumer25A0C48C2:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3BucketE2ADDE75
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - DemoConsumer2ServiceRole94782386
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          SERVICE_NAME: consumer-2
      ReservedConcurrentExecutions: 1
      Timeout: 60
    DependsOn:
      - DemoConsumer2ServiceRoleDefaultPolicyC9C2B244
      - DemoConsumer2ServiceRole94782386
    Metadata:
      aws:cdk:path: demo/DemoConsumer2/Resource
      aws:asset:path: asset.9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028
      aws:asset:property: Code
  DemoConsumer2SqsEventSourcedemoDemoQueue21467F714F9D612B2:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - DemoQueue23A6C79B0
          - Arn
      FunctionName:
        Ref: DemoConsumer25A0C48C2
      BatchSize: 1
    Metadata:
      aws:cdk:path: demo/DemoConsumer2/SqsEventSource:demoDemoQueue21467F714/Resource
  DemoQueue32738C84A:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
    Metadata:
      aws:cdk:path: demo/DemoQueue3/Resource
  DemoQueue3Policy1B28AD9D:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: DemoTopic2BE41B12
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - DemoQueue32738C84A
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: DemoQueue32738C84A
    Metadata:
      aws:cdk:path: demo/DemoQueue3/Policy/Resource
  DemoQueue3demoDemoTopic3BBFFA9C8165D488:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn:
        Ref: DemoTopic2BE41B12
      Endpoint:
        Fn::GetAtt:
          - DemoQueue32738C84A
          - Arn
    Metadata:
      aws:cdk:path: demo/DemoQueue3/demoDemoTopic3BBFFA9C/Resource
  DemoConsumer3ServiceRole5B410B5B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: demo/DemoConsumer3/ServiceRole/Resource
  DemoConsumer3ServiceRoleDefaultPolicy362CF475:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DemoQueue32738C84A
                - Arn
        Version: "2012-10-17"
      PolicyName: DemoConsumer3ServiceRoleDefaultPolicy362CF475
      Roles:
        - Ref: DemoConsumer3ServiceRole5B410B5B
    Metadata:
      aws:cdk:path: demo/DemoConsumer3/ServiceRole/DefaultPolicy/Resource
  DemoConsumer3A7B19986:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3BucketE2ADDE75
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - DemoConsumer3ServiceRole5B410B5B
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          SERVICE_NAME: consumer-3
      Timeout: 60
    DependsOn:
      - DemoConsumer3ServiceRoleDefaultPolicy362CF475
      - DemoConsumer3ServiceRole5B410B5B
    Metadata:
      aws:cdk:path: demo/DemoConsumer3/Resource
      aws:asset:path: asset.9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028
      aws:asset:property: Code
  DemoConsumer3SqsEventSourcedemoDemoQueue326925FCDE3864EBA:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - DemoQueue32738C84A
          - Arn
      FunctionName:
        Ref: DemoConsumer3A7B19986
      BatchSize: 1
    Metadata:
      aws:cdk:path: demo/DemoConsumer3/SqsEventSource:demoDemoQueue326925FCD/Resource
  DemoProducerServiceRole9403AF3E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: demo/DemoProducer/ServiceRole/Resource
  DemoProducerServiceRoleDefaultPolicy87E3E44D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sns:Publish
            Effect: Allow
            Resource:
              Ref: DemoTopic2BE41B12
        Version: "2012-10-17"
      PolicyName: DemoProducerServiceRoleDefaultPolicy87E3E44D
      Roles:
        - Ref: DemoProducerServiceRole9403AF3E
    Metadata:
      aws:cdk:path: demo/DemoProducer/ServiceRole/DefaultPolicy/Resource
  DemoProducer129FEDD3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersbb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4S3Bucket640D52DB
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4S3VersionKey549AE5E4
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4S3VersionKey549AE5E4
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - DemoProducerServiceRole9403AF3E
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          TOPIC_ARN:
            Ref: DemoTopic2BE41B12
      Timeout: 600
    DependsOn:
      - DemoProducerServiceRoleDefaultPolicy87E3E44D
      - DemoProducerServiceRole9403AF3E
    Metadata:
      aws:cdk:path: demo/DemoProducer/Resource
      aws:asset:path: asset.bb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.44.0,@aws-cdk/assets=1.44.0,@aws-cdk/aws-apigateway=1.44.0,@aws-cdk/aws-cloudwatch=1.44.0,@aws-cdk/aws-ec2=1.44.0,@aws-cdk/aws-events=1.44.0,@aws-cdk/aws-iam=1.44.0,@aws-cdk/aws-kms=1.44.0,@aws-cdk/aws-lambda=1.44.0,@aws-cdk/aws-lambda-event-sources=1.44.0,@aws-cdk/aws-logs=1.44.0,@aws-cdk/aws-s3=1.44.0,@aws-cdk/aws-s3-assets=1.44.0,@aws-cdk/aws-s3-notifications=1.44.0,@aws-cdk/aws-sns=1.44.0,@aws-cdk/aws-sns-subscriptions=1.44.0,@aws-cdk/aws-sqs=1.44.0,@aws-cdk/aws-ssm=1.44.0,@aws-cdk/cdk-assets-schema=1.44.0,@aws-cdk/cloud-assembly-schema=1.44.0,@aws-cdk/core=1.44.0,@aws-cdk/cx-api=1.44.0,@aws-cdk/region-info=1.44.0,jsii-runtime=node.js/v12.13.0
Parameters:
  AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3BucketE2ADDE75:
    Type: String
    Description: S3 bucket for asset "9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028"
  AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028S3VersionKeyE290D67C:
    Type: String
    Description: S3 key for asset version "9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028"
  AssetParameters9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028ArtifactHashFECBA59D:
    Type: String
    Description: Artifact hash for asset "9c95616a55841ce86e84dfa0e30d7f85030780287da19e1c5254832c561fc028"
  AssetParametersbb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4S3Bucket640D52DB:
    Type: String
    Description: S3 bucket for asset "bb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4"
  AssetParametersbb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4S3VersionKey549AE5E4:
    Type: String
    Description: S3 key for asset version "bb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4"
  AssetParametersbb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4ArtifactHash979E4914:
    Type: String
    Description: Artifact hash for asset "bb7c7bd692991d1e6c5be8495e87b26dce635ec92e6a7b013127a7284f30d8a4"
